const express = require("express");
const path = require("path");
const app = express();
const publicDir = path.join(__dirname, "public");
app.use(express.static(publicDir, { extensions: ["html"] }));
app.get("/health", (_req, res) => res.json({ ok: true }));
app.get("/api/token", (_req, res) => res.sendFile(path.join(publicDir, "token.json")));
app.get("/{*splat}", (_req, res) => res.sendFile(path.join(publicDir, "index.html")));
const port = process.env.PORT || 3000;
app.listen(port, () => console.log(`MATT website listening on ${port}`));
